# Generated by Django 5.2.17 on 2026-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komoditas', '0002_komoditas_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='komoditas',
            name='is_ekspor',
            field=models.BooleanField(default=False, verbose_name='Apakah ini Komoditi Ekspor?'),
        ),
    ]
