# Generated by Django 5.2.17 on 2026-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komoditas', '0003_komoditas_is_ekspor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eksportir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_company', models.CharField(max_length=200, verbose_name='Profil Company')),
                ('komoditas', models.CharField(max_length=100, verbose_name='Komoditas')),
                ('volume', models.FloatField(default=0, verbose_name='Volume Pengiriman Ekspor')),
                ('satuan', models.CharField(default='kg', max_length=20, verbose_name='Satuan')),
                ('tujuan_ekspor', models.CharField(max_length=200, verbose_name='Tujuan Ekspor')),
            ],
            options={
                'verbose_name_plural': 'Daftar Eksportir',
                'db_table': 'accounts_eksportir',
                'ordering': ['profil_company'],
            },
        ),
        migrations.RemoveField(
            model_name='komoditas',
            name='is_ekspor',
        ),
    ]
